/**
 * CoPantry Design System — design/tailwind.preset.js
 *
 * !! DO NOT EDIT THIS FILE DIRECTLY !!
 * Managed copy — to update design tokens:
 *   1. Edit the canonical source: /tailwind.preset.js (monorepo root)
 *   2. Run:  node scripts/sync-design-tokens.mjs
 *   3. Commit the updated copy in this repo.
 */

// ─── Raw token values ────────────────────────────────────────────────────────
// These are JS constants. The hex strings here must match shared/tokens.css.

export const TOKENS = {
  color: {
    brand: {
      50:  '#fff7ed',
      100: '#ffedd5',
      200: '#fed7aa',
      300: '#fdba74',
      400: '#fb923c',
      500: '#f97316',
      600: '#ea580c',
      700: '#c2410c',
      800: '#9a3412',
      900: '#7c2d12',
    },
    accent: {
      recipes:  '#f97316',
      pantry:   '#16a34a',
      calendar: '#7c3aed',
      shopping: '#2563eb',
      premium:  '#f59e0b',
      danger:   '#f43f5e',
    },
    neutral: {
      50:  '#fafafa',
      100: '#f4f4f5',
      200: '#e4e4e7',
      300: '#d4d4d8',
      400: '#a1a1aa',
      500: '#71717a',
      700: '#3f3f46',
      800: '#27272a',
      900: '#18181b',
      950: '#09090b',
    },
    surface: {
      canvas:       '#faf8f4',
      raised:       '#fffefb',
      dark:         '#18181b',
      darkRaised:   '#1f1f23',
      darkVariant:  '#27272a',
      darkElevated: '#2e2e33',
    },
    status: {
      fresh:           '#10b981',
      freshContainer:  '#d1fae5',
      freshLight:      '#34d399',
      freshDark:       '#059669',
      freshDeep:       '#14532d',
      attention:       '#f59e0b',
      attentionSoft:   '#fef3c7',
      attentionPale:   '#fcd34d',
      attentionLight:  '#fbbf24',
      attentionDark:   '#d97706',
      expired:         '#f43f5e',
      expiredContainer:'#ffe4e6',
      expiredLight:    '#fb7185',
      expiredDark:     '#e11d48',
      danger:          '#ec2020',
      dangerContainer: '#ffe5e5',
      dangerLight:     '#ef6666',
      dangerDark:      '#cc1a1a',
    },
    ai: {
      surface:     '#e0e7ff',
      action:      '#6366f1',
      actionDark:  '#818cf8',
      actionDeep:  '#4f46e5',
      surfaceDark: '#1e1b4b',
    },
    assistant: {
      skyLight: '#38bdf8',
      sky:      '#0ea5e9',
    },
    overlay: {
      scrim:     '#000000',
      scrimSoft: '#cc000000',
      scrimDark: '#e6000000',
    },
    foreground: '#111827', // gray-900

    // Semantic theme tokens — the dark-mode palette. Light defaults + the
    // dark overrides (mirrors shared/tokens.css :root[data-theme="dark"]).
    theme: {
      canvas:        '#f9fafb',
      raised:        '#ffffff',
      sunken:        '#f3f4f6',
      overlay:       '#ffffff',
      content:       '#111827',
      contentMuted:  '#4b5563',
      contentSubtle: '#6b7280',
      line:          '#e5e7eb',
      lineStrong:    '#d1d5db',
      brandContrast: '#ea580c',
      inverse:       '#111827',
      inverseContent:'#ffffff',
    },
    themeDark: {
      canvas:        '#17171a',
      raised:        '#202024',
      sunken:        '#0f0f11',
      overlay:       '#26262b',
      content:       '#ededf0',
      contentMuted:  '#a1a1aa',
      contentSubtle: '#8b8b93',
      line:          '#2e2e33',
      lineStrong:    '#3f3f46',
      brandContrast: '#fb923c',
      inverse:       '#ededf0',
      inverseContent:'#17171a',
    },
  },

  font: {
    body: "'Inter', system-ui, -apple-system, sans-serif",
    logo: "'Poppins', sans-serif",
    mono: "'JetBrains Mono', 'Fira Code', ui-monospace, monospace",
  },

  logo: {
    tracking:     '-0.02em',
    weightCo:     600,
    weightPantry: 400,
  },

  radius: {
    card:  '1rem',    // 16 px — rounded-2xl equivalent
    input: '0.75rem', // 12 px — rounded-xl equivalent
    badge: '9999px',  // pill
  },
}

// ─── Tailwind theme.extend object ────────────────────────────────────────────
// Spread into each project's tailwind.config.js theme.extend.
// Values reference CSS custom properties defined in shared/tokens.css so that
// a single edit to tokens.css updates every compiled stylesheet.

export const twExtend = {
  colors: {
    brand: {
      50:  'var(--color-brand-50)',
      100: 'var(--color-brand-100)',
      200: 'var(--color-brand-200)',
      500: 'var(--color-brand-500)',
      600: 'var(--color-brand-600)',
      700: 'var(--color-brand-700)',
    },
    'accent-recipes':  'var(--color-accent-recipes)',
    'accent-pantry':   'var(--color-accent-pantry)',
    'accent-calendar': 'var(--color-accent-calendar)',
    'accent-shopping': 'var(--color-accent-shopping)',
    'accent-premium':  'var(--color-accent-premium)',
    'accent-danger':   'var(--color-accent-danger)',
    'surface-canvas':  'var(--color-surface-canvas)',
    'surface-raised':  'var(--color-surface-raised)',
    'status-fresh':    'var(--color-status-fresh)',
    'status-attention':'var(--color-status-attention)',
    'status-expired':  'var(--color-status-expired)',
    'status-danger':   'var(--color-status-danger)',
    // Semantic theme tokens (dark-mode palette; flip via [data-theme="dark"])
    canvas:          'var(--color-canvas)',
    raised:          'var(--color-raised)',
    sunken:          'var(--color-sunken)',
    overlay:         'var(--color-overlay)',
    content: {
      DEFAULT: 'var(--color-content)',
      muted:   'var(--color-content-muted)',
      subtle:  'var(--color-content-subtle)',
    },
    line: {
      DEFAULT: 'var(--color-line)',
      strong:  'var(--color-line-strong)',
    },
    'brand-contrast': 'var(--color-brand-contrast)',
    inverse: {
      DEFAULT: 'var(--color-inverse)',
      content: 'var(--color-inverse-content)',
    },
  },

  fontFamily: {
    logo: ['var(--font-logo)'],
    body: ['var(--font-body)'],
    mono: ['var(--font-mono)'],
  },

  borderRadius: {
    card:  'var(--radius-card)',
    input: 'var(--radius-input)',
    badge: 'var(--radius-badge)',
  },
}

export default twExtend
